# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Hoaxify Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
        java-version: 1.8
    - run: npm ci
      working-directory: ./react_frontend
    - run: npm run build --if-present
      working-directory: ./react_frontend
    - name: copy raect to spring static resources
      run: |
        mkdir -p src/main/resources/static
        cp- -a ./react_frontend/build/. src/main/resources/static/
    - name: Build spring
      run: mvn -B package --file pom.xml
      working-directory: ./
     
    
    
     
    - name: SFTP Deploy
  # You may pin to the exact commit or the version.
  # uses: wlixcc/SFTP-Deploy-Action@c6e4d76ad92d7460e93fc66178b52638298adfaa
      uses: wlixcc/SFTP-Deploy-Action@v1.2.2
      with:
     # username
       username: ${{secrets.USERNAME}}
     # your sftp server
       server: ${{secrets.IP}}
     # your sftp server port, default to 22
       ssh_private_key: ${{secrets.SSH}}
       local_path: src/target/Hoaxify-0.0.1-SNAPSHOT.jar
     # files will copy to under remote_path
       remote_path: /home/musty1406 

